web:
  hosts:
    83.226.220.77
  vars:
    domain: site.dev
    web_user: www-data
    web_group: www-data
    ansible_user: jenkins
    ansible_become: True
    ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa
