- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 36000

  - name: "install aptitude"
    apt:
      name: ['aptitude']
      state: latest

  - name: "aptidue update"
    aptitude:
      update_cache: yes
      cache_valid_time: 3600
    
  - name: "install lighttpd"
    aptitude:
      name: ['lighttpd']
      state: latest
  - name: "enable ufw"
    service:
      name: ['ufw']
      state: enabled
      state: started
  
  - name: "set firewall rules"
    # ufw: 
      #s tate: enabled
      # policy: deny

      state: enabled
      rule: limit
      port: ssh
      proto: tcp

    ufw:
      rule: allow
      port: 22
      proto: tcp

    ufw:
      rule: allow
      port: 80
      proto: tcp

  - name: "create www directory"
    file:
      path: /var/www/
      state: directory
      mode: '0775'
      owner: "{{ web_user }}"
      group: "{{ web_group }}"
- name: "create a index file"
  shell -a echo '<html> <body> <h1> This is a website </h1></body></html>' > /var/www/index.hmtl
  shell -a echo {{"server.modules = (
        "mod_indexfile",
        "mod_access",
        "mod_alias",
        "mod_redirect",
)

server.document-root        = "/var/www/html"
server.upload-dirs          = ( "/var/cache/lighttpd/uploads" )
server.errorlog             = "/var/log/lighttpd/error.log"
server.pid-file             = "/run/lighttpd.pid"
server.username             = "www-data"
server.groupname            = "www-data"
server.port                 = 80

# strict parsing and normalization of URL for consistency and security
# https://redmine.lighttpd.net/projects/lighttpd/wiki/Server_http-parseoptsDetails
# (might need to explicitly set "url-path-2f-decode" = "disable"
#  if a specific application is encoding URLs inside url-path)
server.http-parseopts = (
  "header-strict"           => "enable",# default
  "host-strict"             => "enable",# default
  "host-normalize"          => "enable",# default
  "url-normalize-unreserved"=> "enable",# recommended highly
  "url-normalize-required"  => "enable",# recommended
  "url-ctrls-reject"        => "enable",# recommended
  "url-path-2f-decode"      => "enable",# recommended highly (unless breaks app)
 #"url-path-2f-reject"      => "enable",
  "url-path-dotseg-remove"  => "enable",# recommended highly (unless breaks app)
 #"url-path-dotseg-reject"  => "enable",
 #"url-query-20-plus"       => "enable",# consistency in query string
)

index-file.names            = ( "index.php", "index.html" )
url.access-deny             = ( "~", ".inc" )
static-file.exclude-extensions = ( ".php", ".pl", ".fcgi" )

compress.cache-dir          = "/var/cache/lighttpd/compress/"
compress.filetype           = ( "application/javascript", "text/css", "text/html", "text/plain" )

# default listening port for IPv6 falls back to the IPv4 port
## Use ipv6 if available
#include_shell "/usr/share/lighttpd/use-ipv6.pl " + server.port
include_shell "/usr/share/lighttpd/create-mime.conf.pl"
include "/etc/lighttpd/conf-enabled/*.conf"

#server.compat-module-load   = "disable"
server.modules += (
        "mod_compress",
        "mod_dirlisting",
        "mod_staticfile",
)
}}" > /etc/lighttpd.conf


  - name: copy httpd config
    template:
      src: lighttpd.conf
      dest: /etc/lighttpd/lighttpd.conf
      owner: root
      group: root
      mode: '0644'
    notify: restart lighttpd

  handlers:
    - name: restart lighttpd
      service:
        name: lighttpd
        state: restarted
