- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 36000
    
  - name: "install lighttpd"
    apt:
      name: ['lighttpd']
      state: latest
      
  - name: "firewall limit ssh"
    ufw:
      rule: limit
      port: ssh
      proto: tcp
      
  - name: "firewall allow ssh"
    ufw:
      rule: allow
      port: 22
      proto: tcp
      
  - name: "firewall allow http"
    ufw:  
      rule: allow
      port: 80
      proto: tcp
  
  - name: "enable ufw"
    ufw:
      state: enabled  
  
  - name: "restart ufw"
    ufw:
     state: reloaded
  

  - name: "create www directory"
    file:
      path: /var/www/html/
      state: directory
      mode: '0775'
      owner: "www-data"
      group: "www-data"
      recurse: yes
      
  - name: "create an index and a config file"
    shell: rm /var/www/html/* ; echo '<!DOCTYPE html>'  > /var/www/html/index.hmtl ; echo '<html> <body> <h1> This is a website </h1></body></html>' >> /var/www/html/index.hmtl
    notify: restart lighttpd
 
  - name: "set permissions on index.html"
    file:
      path: /var/www/html/index.html
      mode: '0775'
      owner: "www-data"
      group: "www-data"
    
    
  #- name: "set httpd config mode"
  #  template:
  #    src: "/etc/lighttpd/lighttpd.conf"
  #    dest: "/etc/lighttpd/lighttpd.conf"
  #    owner: root
  #    group: root
  #    mode: '0644'
  #  notify: restart lighttpd

  handlers:
    - name: restart lighttpd
      service:
        name: lighttpd
        state: restarted
