- hosts: web
  become: yes
  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 36000

  - name: "install aptitude"
    apt:
      name: "aptitude"
      state: latest

  - name: "aptitude update"
    aptitude:
      update_cache: yes
      cache_valid_time: 3600
    
  - name: "install lighttpd"
    aptitude:
      name: ['lighttpd']
      state: latest
      

  
  - name: "set firewall rules"
    ufw:
      rule: limit
      port: ssh
      proto: tcp
      rule: allow
      port: 22
      proto: tcp
      rule: allow
      port: 80
      proto: tcp
      
   - name: "enable ufw"
    service:
      name: ['ufw']
      state: enabled
      state: restarted

  - name: "create www directory"
    file:
      path: /var/www/
      state: directory
      mode: '0775'
      owner: "web_user"
      group: "web_group"
- name: "create an index and a config file"
  shell: -a echo '<html> <body> <h1> This is a website </h1></body></html>' > /var/www/index.hmtl
 
  #- name: "set httpd config mode"
  #  template:
  #    src: "/etc/lighttpd/lighttpd.conf"
  #    dest: "/etc/lighttpd/lighttpd.conf"
  #    owner: root
  #    group: root
  #    mode: '0644'
  #  notify: restart lighttpd

  handlers:
    - name: restart lighttpd
      service:
        name: lighttpd
        state: restarted
